apps/biblioteca/urls.py
from django.conf.urls import url
from django.views.generic import detail
from django.conf import settings
from django.conf.urls.static import static


from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),

    #URLs para list
    url(r'^autor/function/list$', autor_list, name='function_autor_listar'),
    url(r'^autor/class/list$', AutorView.as_view(), name='class_autor_listar'),

    url(r'^editor/function/list$', editor_list, name='function_editor_listar'),
    url(r'^editor/class/list$', EditorView.as_view(), name='class_editor_listar'),

    url(r'^libro/function/list$', libro_list, name='function_libro_listar'),
    url(r'^libro/class/list$', LibroView.as_view(), name='class_libro_listar'),

    #URLs para nuevo
    url(r'^autor/function/nuevo$', autor_create, name='function_autor_crear'),
    url(r'^autor/class/nuevo$', AutorCreateView.as_view(), name='class_autor_crear'),

    url(r'^editor/function/nuevo$', editor_create, name='function_editor_crear'),
    url(r'^editor/class/nuevo$', EditorCreateView.as_view(), name='class_editor_crear'),

    url(r'^libro/function/nuevo$', libro_create, name='function_libro_crear'),
    url(r'^libro/class/nuevo$', LibroCreateView.as_view(), name='class_libro_crear'),

    #URLs para editar
    url(r'^autor/function/editar/(?P<id_autor>\d+)/', autor_edit, name='function_autor_editar'),
    url(r'^autor/class/editar/(?P<pk>\d+)/', AutorUpdateView.as_view(), name='class_autor_editar'),

    url(r'^editor/function/editar/(?P<id_autor>\d+)/', editor_edit, name='function_editor_editar'),
    url(r'^editor/class/editar/(?P<pk>\d+)/', EditorUpdateView.as_view(), name='class_editor_editar'),

    url(r'^libro/function/editar/(?P<id_autor>\d+)/', libro_edit, name='function_libro_editar'),
    url(r'^libro/class/editar/(?P<pk>\d+)/', LibroUpdateView.as_view(), name='class_libro_editar'),

    #URLs para eliminar
    url(r'^autor/function/eliminar/(?P<id_autor>\d+)/', autor_delete, name='function_autor_eliminar'),
    url(r'^autor/class/eliminar/(?P<pk>\d+)/', AutorDeleteView.as_view(), name='class_autor_eliminar'),

    url(r'^editor/function/eliminar/(?P<id_autor>\d+)/', editor_delete, name='function_editor_eliminar'),
    url(r'^editor/class/eliminar/(?P<pk>\d+)/', EditorDeleteView.as_view(), name='class_editor_eliminar'),

    url(r'^libro/function/eliminar/(?P<id_autor>\d+)/', libro_delete, name='function_libro_eliminar'),
    url(r'^libro/class/eliminar/(?P<pk>\d+)/', LibroDeleteView.as_view(), name='class_libro_eliminar'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misitio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from misitio import settings
from django.conf.urls.static import static

from misitio.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hola/$', hola),
    url(r'^fecha_actual/$', fecha_actual),
    url(r'^fecha/mas/(\d{1,2})/$', horas_adelante),
    url(r'^encabezados/$', encabezados_http, name='encabezados'),
    url(r'^formulario-buscar/$', formulario_buscar),
    url(r'^buscar/$', buscar),
    url(r'^contactos/$', contactos),
    url(r'^contactos/gracias/$', contactos_gracias),
    url(r'^biblioteca/', include('apps.biblioteca.urls', namespace='biblioteca')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/biblioteca/models.py
from django.db import models
import datetime


class Editor(models.Model):
    nombre = models.CharField(max_length=30)
    domicilio = models.CharField(max_length=30)
    ciudad = models.CharField(max_length=30)
    estado = models.CharField(max_length=30)
    pais = models.CharField(max_length=30)
    website = models.URLField(max_length=30)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


class Autor(models.Model):
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=30)
    email = models.EmailField(blank=True, verbose_name="e-mail")

    class Meta:
        ordering = ['nombre']
        verbose_name_plural = "Autores"

    def __str__(self):
        return '%s %s' % (self.apellidos, self.nombre)

class Libro(models.Model):
    titulo = models.CharField(max_length=100)
    autores = models.ManyToManyField(Autor)
    editor = models.ForeignKey(Editor, on_delete=models.CASCADE)
    fecha_publicacion = models.DateField(default=datetime.date.today, blank=True)
    portada = models.ImageField(upload_to="portada", default='default.jpg', blank=True)

    def __str__(self):
        return self.titulo

apps/biblioteca/forms.py
from django import forms

from apps.biblioteca.models import Libro, Editor, Autor


class FormularioEditor(forms.ModelForm):
    class Meta:
        model = Editor

        fields = {
            'nombre',
            'domicilio',
            'ciudad',
            'estado',
            'pais',
            'website',
        }

        labels = {
            'nombre': 'Nombre',
            'domicilio': 'Domicilio',
            'ciudad': 'Ciudad',
            'estado': 'Estado',
            'pais': 'Pais',
            'website': 'Website',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'domicilio': forms.TextInput(attrs={'class': 'form-control'}),
            'ciudad': forms.TextInput(attrs={'class': 'form-control'}),
            'estado': forms.TextInput(attrs={'class': 'form-control'}),
            'pais': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.URLInput(attrs={'class': 'form-control'}),
        }


class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = {
            'nombre',
            'apellidos',
            'email',
        }

        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Apellidos',
            'email': 'Email',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro

        fields = [
            'titulo',
            'autores',
            'editor',
            'fecha_publicacion',
            'portada',
        ]

        labels = {
            'titulo': 'Titulo',
            'autores': 'Autores',
            'editor': 'Editor',
            'fecha_publicacion': 'Fecha Publicacion',
            'portada': 'Portada',
        }

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'autores': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'editor': forms.Select(attrs={'class': 'form-control'}),
            'fecha_publicacion': forms.TextInput(attrs={'class': 'form-control'}),
            'portada': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

apps/biblioteca/views.py
from urllib import request

from django.contrib import messages
from urllib.request import Request

from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest

# Create your views here.


from apps.biblioteca.forms import AutorForm, LibroForm, FormularioEditor
from apps.biblioteca.models import Autor, Libro, Editor

##############################################################################
#############              Vistas Autor                 ######################
##############################################################################
# Vista index
def index(request : HttpRequest) -> HttpResponse:
    return render(request, 'biblioteca/index.html')

# Listado de autores ordenados por id
def autor_list(request: HttpRequest) -> HttpResponse:
    autores = Autor.objects.all().order_by('id')
    contexto = {'autores': autores}
    return render(request, 'biblioteca/autor/autor_list.html', contexto)

# VIsta para crear un autor usando el formulario
def autor_create(request : HttpRequest) -> HttpResponse:
    if request.method == "POST":
         form = AutorForm(request.POST)
         if form.is_valid():
            form.save()
            messages.success(request, 'Autor registrado correctamente')
            return redirect('biblioteca:function_autor_listar')
         else:
             messages.error(request, 'Ocurrio un error al guardar el autor')
    else:
        form = AutorForm()
        print(form)
    return render(request, "biblioteca/autor/autor_form.html", {'form': form})

#Vista para editar la informacion existente de un autor
def autor_edit(request: HttpRequest, id_autor: int) -> HttpResponse:
    autor = Autor.objects.get(id=id_autor)
    if request.method == "GET":
        form = AutorForm(instance=autor)
        print(form)
    else:
        form = AutorForm(request.POST, instance=autor)
        if form.is_valid():
            form.save()
            messages.success(request, 'Autor registrado correctamente')
            return redirect('biblioteca:function_autor_listar')
        else:
            messages.error(request, 'Ocurrio un error al guardar el autor')
    return render(request, 'biblioteca/autor/autor_form.html', {'form': form})

def autor_delete(request: HttpRequest, id_autor: int) -> HttpResponse:
    autor = Autor.objects.get(id=id_autor)
    if request.method == "POST":
        autor.delete()
        messages.success(request, 'Autor eliminado correctamente')
        return redirect('biblioteca:function_autor_listar')
    return render(request, 'biblioteca/autor/autor_delete.html', {'autor': autor})

class AutorView(ListView):
    model = Autor
    template_name = 'biblioteca/autor/autor_list.html'

class AutorCreateView(CreateView):
    model = Autor
    form_class = AutorForm
    template_name = 'biblioteca/autor/autor_form.html'
    success_url = reverse_lazy('biblioteca:class_autor_listar')

    def form_valid(self, form):
        messages.success(self.request, 'Autor registrado exitosamente!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Ocurrio un error al registrar el Autor')
        return super().form_invalid(form)


class AutorUpdateView(UpdateView):
    model = Autor
    form_class = AutorForm
    template_name = 'biblioteca/autor/autor_form.html'
    success_url = reverse_lazy('biblioteca:class_autor_listar')

    def form_valid(self, form):
        messages.success(self.request, 'Autor actualizado exitosamente!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Ocurrio un error al actualizar el Autor')
        return super().form_invalid(form)


class AutorDeleteView(DeleteView):
    model = Autor
    template_name = 'biblioteca/autor/autor_delete.html'
    success_url = reverse_lazy('biblioteca:class_autor_listar')

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Solicitud eliminada correctamente')
        return super(AutorDeleteView, self).delete(request, *args, **kwargs)


##############################################################################
#############              Vistas Editor                ######################
##############################################################################

def editor_list(request : HttpRequest) -> HttpResponse:
    editores = Editor.objects.all().order_by('id')
    contexto = {'editores': editores}
    return render(request, 'biblioteca/editor/editor_list.html', contexto)

def editor_create(request : HttpRequest) -> HttpResponse:
    if request.method == "POST":
         form = FormularioEditor(request.POST)
         if form.is_valid():
            form.save()
            messages.success(request, 'Editor registrado correctamente')
            return redirect('biblioteca:function_editor_listar')
         else:
             messages.error(request, 'Ocurrio un error al guardar el editor')
    else:
        form = FormularioEditor()
        print(form)
    return render(request, "biblioteca/editor/editor_form.html", {'form': form})

def editor_edit(request: HttpRequest, id_editor: int) -> HttpResponse:
    editor = Editor.objects.get(id=id_editor)
    if request.method == "GET":
        form = AutorForm(instance=editor)
    else:
        form = AutorForm(request.POST, instance=editor)
        if form.is_valid():
            form.save()
            messages.success(request, 'Editor actualizado correctamente')
            return redirect('biblioteca:function_autor_listar')
        else:
            messages.error(request, 'Ocurrio un error al actualizar el editor')
    return render(request, 'biblioteca/editor/editor_form.html', {'form': form})

def editor_delete(request: HttpRequest, id_editor: int) -> HttpResponse:
    editor = Editor.objects.get(id=id_editor)
    if request.method == "POST":
        editor.delete()
        messages.success(request, 'Editor eliminado correctamente')
        return redirect('biblioteca:function_editor_listar')
    return render(request, 'biblioteca/editor/libro_delete.html', {'editor': editor})

class EditorView(ListView):
    model = Editor
    template_name = 'biblioteca/editor/editor_list.html'

class EditorCreateView(CreateView):
    model = Editor
    form_class = FormularioEditor
    template_name = 'biblioteca/editor/editor_form.html'
    success_url = reverse_lazy('biblioteca:class_editor_listar')

    def form_valid(self, form):
        messages.success(self.request, 'Autor creado exitosamente!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Ocurrio un error al crear el Editor')
        return super().form_invalid(form)


class EditorUpdateView(UpdateView):
    model = Editor
    form_class = FormularioEditor
    template_name = 'biblioteca/editor/editor_form.html'
    success_url = reverse_lazy('biblioteca:class_editor_listar')

    def form_valid(self, form):
        messages.success(self.request, 'Editor actualizado exitosamente!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Ocurrio un error al actualizar el Editor')
        return super().form_invalid(form)


class EditorDeleteView(DeleteView):
    model = Editor
    template_name = 'biblioteca/editor/editor_delete.html'
    success_url = reverse_lazy('biblioteca:class_editor_listar')

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Solicitud eliminada correctamente')
        return super(EditorDeleteView, self).delete(request, *args, **kwargs)

##############################################################################
#############              Vistas Libro                 ######################
##############################################################################

def libro_list(request : HttpRequest) -> HttpResponse:
    libros = Libro.objects.all().order_by('id')
    contexto = {'libros': libros}
    for libro in libros:
        print(libro.autores)
    return render(request, 'biblioteca/libro/libro_list.html', contexto)

def libro_create(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
         form = LibroForm(request.POST, request.FILES)
         if form.is_valid():
            form.save()
            messages.success(request, 'Libro creado exitosamente!')
            return redirect('biblioteca:function_libro_listar')
         else:
             messages.error(request, 'OCurrió un error al crear el libro')
    else:
        form = LibroForm()
    return render(request, "biblioteca/libro/libro_form.html", {'form': form})

def libro_edit(request: HttpRequest, id_libro: int) -> HttpResponse:
    libro = Libro.objects.get(id=id_libro)
    if request.method == "GET":
        form = Libro(instance=libro)
        print(form)
    else:
        form = LibroForm(request.POST, request.FILES, instance=libro)
        if form.is_valid():
            form.save()
            messages.success(request, 'Libro actualizado exitosamente!')
            return redirect('biblioteca:function_libro_listar')
        else:
            messages.error(request, 'OCurrió un error al actualizar el libro')
    return render(request, 'biblioteca/libro/libro_form.html', {'form': form})

def libro_delete(request: HttpRequest, id_libro: int) -> HttpResponse:
    libro = Libro.objects.get(id=id_libro)
    if request.method == "POST":
        libro.delete()
        messages.success(request, 'Libro eliminado exitosamente!')
        return redirect('biblioteca:function_libro_listar')
    return render(request, 'biblioteca/libro/libro_delete.html', {'libro': libro})

class LibroView(ListView):
    model = Libro
    template_name = 'biblioteca/libro/libro_list.html'

class LibroCreateView(CreateView):

templates/biblioteca/libro/libro_delete.html
{% extends 'nav/nav.html' %}

{% block content %}

    <form method="post">
        {% csrf_token %}

        {% if object %}
            <h3> Desea eliminar el registro de {{ object.titulo }}?</h3>
            <a class="btn btn-default" href="{% url 'biblioteca:class_libro_listar' %}"> Cancelar</a>
        {% else %}
            <h3> Desea eliminar el registro de {{ libro.titulo }}?</h3>
            <a class="btn btn-default" href="{% url 'biblioteca:function_libro_listar' %}"> Cancelar</a>
        {% endif %}
        <button class="btn btn-danger" type="submit">Sí, eliminar</button>

    </form>

{%  endblock %}

templates/biblioteca/libro/libro_form.html
{% extends 'nav/nav.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data" class="border p-4 rounded shadow">
                {% csrf_token %}
                {{ form.as_table }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{%  endblock %}

templates/biblioteca/libro/libro_list.html
{% extends 'nav/nav.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col">
        <div class="table-responsive">
            <table class="table table-bordered text-center">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>Titulo</td>
                        <td>Autores</td>
                        <td>libro</td>
                        <td>Fecha de publicación</td>
                        <td>Portada</td>
                    </tr>
                </thead>
                    <tbody>
                        {% if object_list %}
                            {% for libro in object_list %}
                                <tr>
                                    <td>{{ libro.id }}</td>
                                    <td>{{ libro.titulo }}</td>
                                    <td>
                                        {% for autor in libro.autores.all %}
                                            {{ autor }}
                                        {% endfor %}
                                    </td>
                                    <td>{{ libro.editor }}</td>
                                    <td>{{ libro.fecha_publicacion }}</td>
<!--                                    <td>{{ libro.portada }}</td>-->
                                    {% if libro.portada %}
                                        <td>
                                            <a href="{% url 'biblioteca:class_libro_editar' libro.id %}" > <img src="{{ libro.portada.url }}" alt="{{ libro.titulo }}" width="100"> </a>
                                        </td>
                                    {% else %}
                                        <td> No hay imagen disponible </td>
                                    {% endif %}
                                    <td>
                                        <a class="btn btn-primary" href="{% url 'biblioteca:class_libro_editar' libro.id %}">Editar</a>
                                        <a class="btn btn-danger" href="{% url 'biblioteca:class_libro_eliminar' libro.id %}">Eliminar</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% elif libros %}
                            {% for libro in libros %}
                                <tr>
                                    <td>{{ libro.id }}</td>
                                    <td>{{ libro.titulo }}</td>
                                    <td>

                                        {% for autor in libro.autores.all %}
                                            {{ autor }}
                                            <br>
                                        {% endfor %}
                                    </td>
                                    <td>{{ libro.editor }}</td>
                                    <td>{{ libro.fecha_publicacion }}</td>
                                    {% if libro.portada %}
                                        <td>
                                            <a href="{% url 'biblioteca:class_libro_editar' libro.id %}" > <img src="{{ libro.portada.url }}" alt="{{ libro.titulo }}" width="100"> </a>
                                        </td>
                                    {% else %}
                                        <td> No hay imagen disponible </td>
                                    {% endif %}
                                    <td>
                                        <a class="btn btn-primary" href="{% url 'biblioteca:class_libro_editar' libro.id %}">Editar</a>
                                        <a class="btn btn-danger" href="{% url 'biblioteca:class_libro_eliminar' libro.id %}">Eliminar</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="7">
                                <h1>No hay registros de libros</h1>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
        </table>
    </div>
    </div>
</div>
{% endblock %}