misitio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from misitio import settings
from django.conf.urls.static import static

from misitio.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hola/$', hola),
    url(r'^fecha_actual/$', fecha_actual),
    url(r'^fecha/mas/(\d{1,2})/$', horas_adelante),
    url(r'^encabezados/$', encabezados_http, name='encabezados'),
    url(r'^formulario-buscar/$', formulario_buscar),
    url(r'^buscar/$', buscar),
    url(r'^contactos/$', contactos),
    url(r'^contactos/gracias/$', contactos_gracias),
    url(r'^biblioteca/', include('apps.biblioteca.urls', namespace='biblioteca')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misitio/forms.py
from django import forms




class FormularioContactos(forms.Form):
    asunto = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label="Tu Email")
    mensaje = forms.CharField(widget=forms.Textarea)

    def clean_mensaje(self):
        mensaje = self.cleaned_data['mensaje']
        num_palabras = len(mensaje.split())
        if num_palabras < 4:
            raise forms.ValidationError('Se requieren minimo 4 palabras')
        return mensaje

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

    <h1>Mi sitio web</h1>
    {% block content %} {% endblock %}
    {% block footer %}
    {% endblock %}
    <hr>
    <p> Gracias por visitar nuestro sitio web </p>
</body>
</html>k

templates/encabezados.html
{% extends 'base.html' %}


{% block content %}

    {% for atributo in atributos_meta %}

        <p> {{ atributo }} </p>

    {% endfor %}

{% endblock %}

templates/fecha_actual.html
{% extends 'base.html' %}

<% block title %> La fecha actual <% endoblock %>

{% block content %}

    <p> Hoy es: {{ fecha_actual }} </p>
    <h1>MI titulo</h1>

{% endblock %}

templates/formulario-contactos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contactanos</title>

    <style type="text/css" >
        ul.errorlist{
            margin:0;
            padding: 0;
        }
        .errorlist li{
            background-color: red;
            color: white;
            display: block;
            font-size: 10px;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
    </style>
</head>
<body>
    <h1> Contactanos </h1>
{% if form.errors %}
<!--    <ul>
        {% for error in errors %}
            <li> {{ error }} </li>
        {% endfor %}
    </ul>-->
    <p style="color: red;"> Por favor complete lo siguiente </p>
{% endif %}

<form action="/contactos/" method="post">
    {% csrf_token %}
<!--    <p> Asunto: <input type="text" name="asunto" value="{{ asunto }}"></p>-->
<!--    <p> E-mail (opcional): <input type="text" name="email" value="{{ email }}"> </p>-->
<!--    <p> Mensaje: <textarea name="mensaje" rows="10" cols="50"> {{ mensaje }}</textarea></p>-->
<!--    <input type="submit" value="Enviar">-->

<!--    <table>-->
<!--        {{ form.as_table }}-->
<!--    </table>-->

    <div class="field">
        {{ form.asunto.errors }}
            <label for="id_asunto"> Asunto </label>
        {{ form.asunto }}
    </div>

    <div class="field">
        {{ form.email.errors }}
        <label for="id_email"> E-mail </label>
        {{ form.email }}
    </div>

    <div class="field">
        {{ form.mensaje.errors }}
            <label for="id_mensaje"> Mensaje </label>
        {{ form.mensaje }}
    </div>

    <input type="submit" value="Enviar">
</form>

</body>
</html>

templates/formulario_buscar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buscar</title>
</head>
<body>

    {% if errors %}
        <ul>
            {% for error in errors %}
                <li style="color: red">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="/buscar/" method="get" >
        <input type="text" name="q">
        <input type="submit" value="Buscar">

    </form>

</body>
</html>

templates/gracias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GRACIAS, EN BREVE TE CONTACTAMOS :)</title>
</head>
<body>
  <h1>GRACIAS, EN BREVE TE CONTACTAMOS :)</h1>

</body>
</html>

templates/horas_adelante.html
{% extends "base.html" %}

{% block title %} Fecha futura {% endblock %}

{% block content %}

<h1>ESte es h1</h1>

<p> En {{ horas }} hora(s) , la fecha sera: {{ hora_siguiente }}.</p>

<h3> Hola </h3>

{% endblock %}

templates/resultados.html
<p> Estas buscando <strong> {{ query }} </strong></p>

{% if libros %}
    <p> Libros encontrados: {{ libros | length }} libro {{ libros | pluralize }} </p>
    <ul>
        {% for libro in libros %}
            <li> {{ libro }} </li>
        {% endfor %}
    </ul>
{% else %}

    <p> Ningun libro coincide con el criterio de busqueda </p>

{% endif %}