apps/biblioteca/urls.py
from django.conf.urls import url
from django.views.generic import detail
from django.conf import settings
from django.conf.urls.static import static


from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),

    #URLs para list
    url(r'^autor/function/list$', autor_list, name='function_autor_listar'),
    url(r'^autor/class/list$', AutorView.as_view(), name='class_autor_listar'),

    url(r'^editor/function/list$', editor_list, name='function_editor_listar'),
    url(r'^editor/class/list$', EditorView.as_view(), name='class_editor_listar'),

    url(r'^libro/function/list$', libro_list, name='function_libro_listar'),
    url(r'^libro/class/list$', LibroView.as_view(), name='class_libro_listar'),

    #URLs para nuevo
    url(r'^autor/function/nuevo$', autor_create, name='function_autor_crear'),
    url(r'^autor/class/nuevo$', AutorCreateView.as_view(), name='class_autor_crear'),

    url(r'^editor/function/nuevo$', editor_create, name='function_editor_crear'),
    url(r'^editor/class/nuevo$', EditorCreateView.as_view(), name='class_editor_crear'),

    url(r'^libro/function/nuevo$', libro_create, name='function_libro_crear'),
    url(r'^libro/class/nuevo$', LibroCreateView.as_view(), name='class_libro_crear'),

    #URLs para editar
    url(r'^autor/function/editar/(?P<id_autor>\d+)/', autor_edit, name='function_autor_editar'),
    url(r'^autor/class/editar/(?P<pk>\d+)/', AutorUpdateView.as_view(), name='class_autor_editar'),

    url(r'^editor/function/editar/(?P<id_autor>\d+)/', editor_edit, name='function_editor_editar'),
    url(r'^editor/class/editar/(?P<pk>\d+)/', EditorUpdateView.as_view(), name='class_editor_editar'),

    url(r'^libro/function/editar/(?P<id_autor>\d+)/', libro_edit, name='function_libro_editar'),
    url(r'^libro/class/editar/(?P<pk>\d+)/', LibroUpdateView.as_view(), name='class_libro_editar'),

    #URLs para eliminar
    url(r'^autor/function/eliminar/(?P<id_autor>\d+)/', autor_delete, name='function_autor_eliminar'),
    url(r'^autor/class/eliminar/(?P<pk>\d+)/', AutorDeleteView.as_view(), name='class_autor_eliminar'),

    url(r'^editor/function/eliminar/(?P<id_autor>\d+)/', editor_delete, name='function_editor_eliminar'),
    url(r'^editor/class/eliminar/(?P<pk>\d+)/', EditorDeleteView.as_view(), name='class_editor_eliminar'),

    url(r'^libro/function/eliminar/(?P<id_autor>\d+)/', libro_delete, name='function_libro_eliminar'),
    url(r'^libro/class/eliminar/(?P<pk>\d+)/', LibroDeleteView.as_view(), name='class_libro_eliminar'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misitio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from misitio import settings
from django.conf.urls.static import static

from misitio.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hola/$', hola),
    url(r'^fecha_actual/$', fecha_actual),
    url(r'^fecha/mas/(\d{1,2})/$', horas_adelante),
    url(r'^encabezados/$', encabezados_http, name='encabezados'),
    url(r'^formulario-buscar/$', formulario_buscar),
    url(r'^buscar/$', buscar),
    url(r'^contactos/$', contactos),
    url(r'^contactos/gracias/$', contactos_gracias),
    url(r'^biblioteca/', include('apps.biblioteca.urls', namespace='biblioteca')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/nav/nav.html
{% load static %}

<html lang="es">
<head>
    {%  block extrastatic %}
    {%  endblock %}
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <title>{%  block title %} Title {% endblock %}</title>
</head>

<body>

<div class="container">
{% block navbar %}
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                 <nav class="navbar navbar-default">
                     <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'biblioteca:index' %}">Home</a>

                        </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                         <ul class="nav navbar-nav">
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Biblioteca<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="{% url 'biblioteca:function_autor_listar' %}">Autores (Function View)</a></li>
                                 <li><a href="{% url 'biblioteca:class_autor_listar' %}">Autores (Class View)</a></li>
                                 <li><a href="{% url 'biblioteca:function_libro_listar' %}">Libro (Function View)</a></li>
                                 <li><a href="{% url 'biblioteca:class_libro_listar' %}">Libro (Class View)</a></li>
                                 <li><a href="{% url 'biblioteca:function_editor_listar' %}">Editor (Function View)</a></li>
                                 <li><a href="{% url 'biblioteca:class_editor_listar' %}">Editor (Class View)</a></li>
                              </ul>
                             </li>
                         </ul>
                         <ul class="nav navbar-nav">
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Crear<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="{% url 'biblioteca:function_autor_crear' %}">Crear Autor (Function View)</a></li>
                                 <li><a href="{% url 'biblioteca:class_autor_crear' %}">Crear Autor (Class View)</a></li>
                                 <li><a href="{% url 'biblioteca:function_libro_crear' %}">Crear Libro (Function View)</a></li>
                                 <li><a href="{% url 'biblioteca:class_libro_crear' %}">Crear Libro (Class View)</a></li>
                                 <li><a href="{% url 'biblioteca:function_editor_crear' %}">Crear Editor (Function View)</a></li>
                                 <li><a href="{% url 'biblioteca:class_editor_crear' %}">Crear Editor (Class View)</a></li>
                              </ul>
                             </li>
                         </ul>
                         <ul class="nav navbar-nav navbar-right">
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="#">Salir</a></li>
                              </ul>
                            </li>
                         </ul>
                        </div>
                    </div>
                </nav>
            </div>
              </div>
          </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        {% if message.tags %}
                            {% if message.tags == 'error' %}
                                <li {% if message.tags %} class="alert alert-danger"{% endif %} > {{ message }} </li>
                            {% else %}
                                <li {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} > {{ message }}</li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endif %}
      </div>

   {% endblock %}
</div>

{% block content %}
{% endblock %}

{%  block extrajs %}
{%  endblock %}

</body>

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{%  static 'js/bootstrap.min.js'%}"></script>

</html>